language: cpp
dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt install -y -qq mesa-utils freeglut3-dev g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

before_script:
  - mkdir Build
  - cd Build
  - cmake ..

script: make
